### ISSUE TITLE
关于所有接口都要继承基类？？

### ISSUE THREAD

**Issue by zhangyandong** [CoderLXWang/LXNetwork#1]
关于所有接口都要继承基类新建一个类，这个觉得不太好，可否留个QQ讨论下？  我的QQ 458511381

**Comment by CoderLXWang** [comment]
@zhangyandong 那些代理不作为基类属性是为了避免基类过于臃肿，造成每个接口子类意义不明，当然这也要看个人需求呗，一切皆对象，以前用的就是你说那种，用过这种模式觉得这样写起来是麻烦， 但是用起来更明确，也更容易维护
